spring:
  application:
    name: fondue
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formatsql: true
    database: ${DB}
    database-platform: ${DB_DIALECT}
  output:
    ansi:
      enabled: ALWAYS
