spring:
  application:
    name: fondue
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: moreno
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        formatsql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS
